imports:
  - php

filter:
  excluded_paths:
    - "vendor/*"
    - "docs/*"

checks:
  php:
    code_rating: true
    duplication: true

build:
  image: default-jammy

  environment:
    variables:
      XDEBUG_MODE: coverage

  nodes:
    analysis:
      resources:
        cpus: 4    
      environment:
        php: 8.2
      dependencies:
        override:
          - composer install --no-interaction --prefer-dist
      tests:
        override:
          - command: vendor/bin/phpunit --colors=never --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: php-clover
          - php-scrutinizer-run


    nodes:
        analysis:
            resources:
                cpus: 4