imports:
  - php

filter:
  excluded_paths:
    - "vendor/*"
    - "docs/*"

checks:
  php:
    code_rating: true
    duplication: true

build:
  image: default-jammy

  nodes:
    analysis:
      environment:
        php: 8.3
      dependencies:
        override:
          - composer install --no-interaction --prefer-dist
          - composer dump-autoload -o
      tests:
        override:
          - composer lint
          - vendor/bin/phpunit --colors=never --display-warnings --display-deprecations
          - composer analyse
          - php-scrutinizer-run
